name: Deploy

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Install Cosign
      uses: sigstore/cosign-installer@v3.4.0

    - name: Verify image signature
      env:
        IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/devops-labs:latest
        GITHUB_ISSUER: https://token.actions.githubusercontent.com
        CERT_IDENTITY_REGEXP: https://github.com/.*/IATD-DevSecOps/.github/workflows/ci-pipeline.yml.*
      run: |
        cosign verify $IMAGE  --certificate-identity-regexp $CERT_IDENTITY_REGEXP  --certificate-oidc-issuer $GITHUB_ISSUER